---
# Edge Calculator Deployment
# Calculates similarity scores between users in the matching queue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: g-match-edge-calculator
  namespace: g-match
  labels:
    app: g-match
    component: edge-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: g-match
      component: edge-calculator
  template:
    metadata:
      labels:
        app: g-match
        component: edge-calculator
    spec:
      # Exclude control-plane node
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: edge-calculator
        image: ghcr.io/ysa5347/g-match-backend-matcher:latest
        env:
        - name: SCRIPT_NAME
          value: "edge_calculator.py"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: g-match-secret
              key: REDIS_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: g-match-secret
              key: DB_PASSWORD
        - name: EDGE_POLLING_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: EDGE_POLLING_INTERVAL
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "150m"

---
# Match Scheduler Deployment
# Runs matching algorithm periodically to create matches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: g-match-scheduler
  namespace: g-match
  labels:
    app: g-match
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: g-match
      component: scheduler
  template:
    metadata:
      labels:
        app: g-match
        component: scheduler
    spec:
      # Exclude control-plane node
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: scheduler
        image: ghcr.io/ysa5347/g-match-backend-matcher:latest
        env:
        - name: SCRIPT_NAME
          value: "match_scheduler.py"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: g-match-secret
              key: REDIS_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: g-match-secret
              key: DB_PASSWORD
        - name: SCHEDULER_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: SCHEDULER_INTERVAL
        - name: MATCH_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: g-match-matcher-config
              key: MATCH_THRESHOLD
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "150m"
