---
# Django Migration Job
# Usage:
#   kubectl apply -f migration-job.yaml
#   kubectl wait --for=condition=complete job/g-match-migrate -n g-match --timeout=600s
#   kubectl logs job/g-match-migrate -n g-match
#
# Re-run (delete old job first):
#   kubectl delete job g-match-migrate -n g-match --ignore-not-found && kubectl apply -f migration-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: g-match-migrate
  namespace: g-match
  labels:
    app: g-match
    component: migration
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 600
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: g-match
        component: migration
    spec:
      # Exclude control-plane node
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      imagePullSecrets:
      - name: ghcr-secret
      restartPolicy: Never

      initContainers:
      - name: wait-for-mysql
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          echo "Waiting for MySQL at mysql:3306..."
          until nc -z mysql 3306; do
            echo "MySQL not ready, retrying in 3s..."
            sleep 3
          done
          echo "MySQL is ready!"
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"

      containers:
      - name: migrate
        image: ghcr.io/ysa5347/g-match-backend:latest
        command:
        - sh
        - -c
        - |
          echo "=== G-Match Migration Job ==="
          echo "DB_HOST=$DB_HOST"
          echo "DB_PORT=$DB_PORT"
          echo "DB_NAME=$DB_NAME"
          echo "DB_USER=$DB_USER"
          echo "Attempting migration..."
          python manage.py migrate --noinput
          echo "=== Migration Complete ==="
        envFrom:
        - configMapRef:
            name: g-match-config
        - secretRef:
            name: g-match-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
